"""initial schema

Revision ID: cfa1bb375bfb
Revises: 
Create Date: 2026-06-06 01:21:43.150863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfa1bb375bfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_keys_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_api_key', 'documents', ['api_key_id'], unique=False)
    op.create_index('idx_documents_checksum', 'documents', ['checksum'], unique=False)
    op.create_index('idx_documents_uploaded', 'documents', ['uploaded_at'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_api_key', 'usage_logs', ['api_key_id', 'created_at'], unique=False)
    op.create_index('idx_usage_created', 'usage_logs', ['created_at'], unique=False)
    op.create_index('idx_usage_status', 'usage_logs', ['status_code'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schema_name', sa.String(length=50), nullable=True),
    sa.Column('requested_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('include_confidence', sa.Boolean(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_api_key', 'extraction_jobs', ['api_key_id'], unique=False)
    op.create_index('idx_jobs_batch', 'extraction_jobs', ['batch_id'], unique=False)
    op.create_index('idx_jobs_document_id', 'extraction_jobs', ['document_id'], unique=False)
    op.create_index('idx_jobs_queued_at', 'extraction_jobs', ['queued_at'], unique=False)
    op.create_index('idx_jobs_status', 'extraction_jobs', ['status'], unique=False)
    op.create_table('extraction_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_ai_response', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_results_created_at', 'extraction_results', ['created_at'], unique=False)
    op.create_index('idx_results_job_id', 'extraction_results', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_results_job_id', table_name='extraction_results')
    op.drop_index('idx_results_created_at', table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index('idx_jobs_status', table_name='extraction_jobs')
    op.drop_index('idx_jobs_queued_at', table_name='extraction_jobs')
    op.drop_index('idx_jobs_document_id', table_name='extraction_jobs')
    op.drop_index('idx_jobs_batch', table_name='extraction_jobs')
    op.drop_index('idx_jobs_api_key', table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index('idx_usage_status', table_name='usage_logs')
    op.drop_index('idx_usage_created', table_name='usage_logs')
    op.drop_index('idx_usage_api_key', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index('idx_documents_uploaded', table_name='documents')
    op.drop_index('idx_documents_checksum', table_name='documents')
    op.drop_index('idx_documents_api_key', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_active', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
